name: singleton_macro
description: A Dart package that provides a `Singleton` macro to transform classes into singletons automatically.
version: 0.0.2-dev.2
repository: https://github.com/Antinna/singleton_macro
homepage: https://github.com/antinna/singleton_macro
issue_tracker: https://github.com/antinna/singleton_macro/issues
documentation: https://github.com/antinna/singleton_macro#readme
license: MIT

environment:
  sdk: ^3.6.0-36.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  macros: ^0.1.2-main.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

# Additional metadata

screenshots:
  
  - url: https://github.com/antinna/singleton_macro/screenshots/screenshot1.png
    description: Example output of the Singleton macro applied to a class.
  - url: https://github.com/antinna/singleton_macro/screenshots/screenshot2.png
    description: Demonstration of the Singleton macro in use.
funding:
  - https://github.com/sponsors/Manishmg3994
social:
  github: antinna
  youtube: https://www.youtube.com/@antinna

# Additional tags to help with discovery
topics:
  - dart
  - macros
  - singleton
  - design-patterns
  - utilities
publish_to: https://pub.dev
# scripts:
#   # rps test
#   test: "flutter pub publish --dry-run"
#   # rps publish
#   publish: "flutter pub publish"
